package ru.s100p.shared.constants;

public enum KafkaTopicsConstants {
    USER_REGISTERED,
    USER_PROFILE_UPDATED,
    COURSE_CREATED,
    COURSE_UPDATED,
    ENROLLMENT_CREATED,
    LESSON_COMPLETED,
    PAYMENT_PROCESSED,
    PAYMENT_FAILED,
    NOTIFICATION_REQUESTED;
}
